
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AboutUs = lazy(() => import("./pages/AboutUs.tsx"));
const Acumatica = lazy(() => import("./pages/Acumatica.tsx"));
const Admin = lazy(() => import("./pages/Admin.tsx"));
const AdminDashboard = lazy(() => import("./pages/AdminDashboard.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const SapByDesign = lazy(() => import("./pages/SapByDesign.tsx"));
const SapS4Hana = lazy(() => import("./pages/SapS4Hana.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/about-us", element: <AboutUs />},
	{ path: "/aboutus", element: <AboutUs />},
	{ path: "/acumatica", element: <Acumatica />},
	{ path: "/admin", element: <Admin />},
	{ path: "/admin-dashboard", element: <AdminDashboard />},
	{ path: "/admindashboard", element: <AdminDashboard />},
	{ path: "/", element: <App />},
	{ path: "/sap-by-design", element: <SapByDesign />},
	{ path: "/sapbydesign", element: <SapByDesign />},
	{ path: "/sap-s4hana", element: <SapS4Hana />},
	{ path: "/saps4hana", element: <SapS4Hana />},

];
